### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by simon-p-r** [SheetJS/js-harb#7]
Hello

I was trying to fix issue #6 on a Windows box however even though I can use 'make' on my system it is failing when running make init with following error.

``` js
D:\Modules\js-harb>make init
git submodule init
git submodule update
Submodule path 'test_files': checked out 'f5f97701f1533b5db82d2d674d362f5db680b737'
git submodule foreach git pull origin master
Entering 'test_files'
From https://github.com/SheetJS/test_files
 * branch            master     -> FETCH_HEAD
Updating f5f9770..8ab3308
Fast-forward
 Makefile                 |   3 ++-
 README.md                |  10 +++++++++-
 hyperlink_no_rels.xlsb   | Bin 0 -> 8686 bytes
 hyperlink_no_rels.xlsm   | Bin 0 -> 9347 bytes
 hyperlink_no_rels.xlsx   | Bin 0 -> 9316 bytes
 phpexcel_bad_cfb_dir.xls | Bin 0 -> 88064 bytes
 6 files changed, 11 insertions(+), 2 deletions(-)
 create mode 100644 hyperlink_no_rels.xlsb
 create mode 100644 hyperlink_no_rels.xlsm
 create mode 100644 hyperlink_no_rels.xlsx
 create mode 100644 phpexcel_bad_cfb_dir.xls
git submodule foreach make
Entering 'test_files'
make[1]: Entering directory `d:/Modules/js-harb/test_files'
svn co http://svn.apache.org/repos/asf/poi/trunk/test-data/spreadsheet/ apachepoi
process_begin: CreateProcess(NULL, svn co http://svn.apache.org/repos/asf/poi/trunk/test-data/spreadsheet/ apachepoi, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: *** [apachepoi] Error 2
make[1]: Leaving directory `d:/Modules/js-harb/test_files'
Stopping at 'test_files'; script returned non-zero status.
make: *** [init] Error 1
```

Any help would be appreciated.

**Comment by SheetJSDev** [comment]
There are quite a few dependencies on coreutils and other command line tools like `svn` and `git`.  I have not tested but I assume cygwin should work.

**Comment by SheetJSDev** [comment]
@simon-p-r so the entire set of repos depend on the availability of:

- make 
- bash, cat, cp, rm, awk, grep, sed, mkdir
- git, svn, hg

Some of these can be removed with some structural changes.  For example, `svn` and `hg` are used for downloading test files.  Basically, part of our test suite involves spamming a bunch of files and some of them come from other project bug trackers.  Apache POI has quite a few good corner cases.  Since the licensing terms are unclear, the test_files repo itself doesn't save those files; it merely references them and your computer downloads the test files.  That process failed.

I'm not sure of the best way forward.  I tested against cygwin and things seem to work.  From my understanding, setting up [git with bash and friends](https://git-for-windows.github.io/) and [mercurial](https://www.mercurial-scm.org/wiki/Download#Windows) and [subversion](http://subversion.apache.org/packages.html#windows) should theoretically suffice but I have not tested.

Will close the issue here and open a new one in js-xlsx since it affects that project as well
